id: IA1868D1B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:31:42+00:00'
last_modified: '2022-06-08T01:17:59.062170+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25695
  title: མཚོ་ལྷོའི་སྒྲ་སྙན་ངག་གི་རོལ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    59A2:
      image_group_id: I1KG25697
      title: ''
      total_pages: 305
      order: 1
      base_file: 59A2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
