id: P004468
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25695
  title: མཚོ་ལྷོའི་སྒྲ་སྙན་ངག་གི་རོལ་མཚོ།
  author: ''
  volumes:
    a6f6537dd4344e8c84d40349e9a73372:
      image_group_id: I1KG25697
      title: ''
      volume_number: 1
      total_pages: 305
      base_file: v001.txt
