id: P004468
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 11:24:16.589987
source_metadata:
  id: bdr:W1KG25695
  title: མཚོ་ལྷོའི་སྒྲ་སྙན་ངག་གི་རོལ་མཚོ།
  author: ''
  volumes:
    a6f6537dd4344e8c84d40349e9a73372:
      image_group_id: I1KG25697
      title: ''
      volume_number: 1
      total_pages: 305
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
